apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apps/openebs.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.5/config/manifests/metallb-native.yaml
  - apps/metallb-ippool.yaml
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.10.1/deploy/static/provider/baremetal/deploy.yaml
  - apps/prometheus.yaml
