apiVersion: v1
kind: Namespace
metadata:
  name: openebs
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
spec:
  project: default
  source:
    chart: openebs
    repoURL: https://openebs.github.io/charts
    targetRevision: "3.9.0"
    helm:
      releaseName: openebs
      valuesObject:
        localprovisioner:
          hostpathClass:
            enabled: true
            isDefaultClass: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
