apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: "25.21.0"
    helm:
      releaseName: prometheus
      valuesObject:
        server:
          persistentVolume:
            storageClass: openebs-hostpath
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - "prometheus.rajawatshome.com"
        alertmanager:
          persistentVolume:
            enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
